version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - alaya
  - apalis
  - clippy
  - cust
  - direnv
  - dotenv
  - fsrs
  - haru
  - hnsw
  - iden
  - insel
  - kwaa
  - moeru
  - msvc
  - nemori
  - nixpkgs
  - ollama
  - oper
  - paradedb
  - pgvector
  - pkgs
  - pkill
  - plast
  - plastmem
  - pname
  - prefs
  - qwen
  - retrievability
  - rustc
  - rustls
  - schemars
  - seaql
  - serde
  - sonarjs
  - sqlx
  - utoipa
  - uuidv
  - vchord
  - waifu
  - xsai
ignoreWords: []
import: []
